add errors

diff --git a/actions/setup-safe-chain/action.yml b/actions/setup-safe-chain/action.yml
--- a/actions/setup-safe-chain/action.yml
+++ b/actions/setup-safe-chain/action.yml
@@ -22,7 +22,8 @@ runs:
       run: |
         set -e
         if ! [ -x "$(command -v curl)" ]; then
-          sudo apt update && sudo apt install -qy curl
+          sudo apt update || error "Could not run apt update" 98
+          sudo apt install -qy curl || error "Could not run apt install -qy curl" 99
         fi
         INSTALL_DIR="${HOME}/.safe-chain/bin"
         REPO_URL="https://github.com/AikidoSec/safe-chain"
@@ -92,7 +93,7 @@ runs:
             # Create installation directory
             if [ ! -d "$INSTALL_DIR" ]; then
                 echo "Creating installation directory: $INSTALL_DIR"
-                mkdir -p "$INSTALL_DIR" || echo "Failed to create directory $INSTALL_DIR"
+                mkdir -p "$INSTALL_DIR" || error "Failed to create directory $INSTALL_DIR" 105
             fi
 
             # Download binary
@@ -105,8 +106,8 @@ runs:
 
             # Rename and make executable
             FINAL_FILE="${INSTALL_DIR}/safe-chain"
-            mv "$TEMP_FILE" "$FINAL_FILE" || error "Failed to move $TEMP_FILE to $FINAL_FILE" 105
-            chmod +x "$FINAL_FILE" || error "Failed to make $FINAL_FILE executable" 106
+            mv "$TEMP_FILE" "$FINAL_FILE" || error "Failed to move $TEMP_FILE to $FINAL_FILE" 106
+            chmod +x "$FINAL_FILE" || error "Failed to make $FINAL_FILE executable" 107
 
             echo "Binary installed to: $FINAL_FILE"
 
@@ -117,12 +118,12 @@ runs:
             # Execute safe-chain setup
             echo "Running safe-chain $SETUP_CMD $SETUP_ARGS..."
             if ! "$FINAL_FILE" $SETUP_CMD $SETUP_ARGS; then
-                error "safe-chain was installed but setup encountered issues." 107
+                error "safe-chain was installed but setup encountered issues." 108
             fi
 
             # Add config to remove cooldown (temp fix to avoid break CI)
-            mkdir ~/.aikido || error "Could not create dir ~/.aikido" 108
-            echo '{"minimumPackageAgeHours": 0}' > ~/.aikido/config.json || error "Could not create config file." 109
+            mkdir ~/.aikido || error "Could not create dir ~/.aikido" 109
+            echo '{"minimumPackageAgeHours": 0}' > ~/.aikido/config.json || error "Could not create config file." 110
         }
         main "$@"
       env:
