update safe-chain to 1.3.3 & macos support (#59)
* update safe-chain to 1.3.3

* update safe-chain to 1.3.3

diff --git a/actions/setup-safe-chain/action.yml b/actions/setup-safe-chain/action.yml
--- a/actions/setup-safe-chain/action.yml
+++ b/actions/setup-safe-chain/action.yml
@@ -4,12 +4,18 @@ inputs:
   version:
     type: string
     required: true
-    default: "1.3.2"
-  checksum:
+    default: "1.3.3"
+  checksum-linux-x64:
     type: string
     required: true
-    description: "SHA256 hash of the safe-chain binary file."
-    default: "c0bb727d49c2c699a4a0b651fd45804219f3fb3a5d22e835e9c433b86650c753"
+    description: "SHA256 hash of the safe-chain binary file for linux-x64."
+    default: "ba57cba81e13a920a877bc5767c38494578d1e75cf565f87138c81916a67cc31"
+  checksum-macos-arm64:
+    type: string
+    required: true
+    description: "SHA256 hash of the safe-chain binary file for macos-arm64."
+    default: "e6ab4f595164f3423aae537bebd4b838d4db761b5f668997d32bd7319194724c"
+
 
 runs:
   using: "composite"
@@ -66,11 +72,11 @@ runs:
         # Check file integrity
         check_file() {
             file="$1"
+            arch="$2"
 
             hash=$(sha256sum $file | awk '{ print $1 }')
-
-            if [ "$hash" != "$CHECKSUM" ]; then
-                error "Invalid checksum. Got $hash ; expected $CHECKSUM ($?)" 104
+            if [ "$hash" != "$CHECKSUM-$arch" ]; then
+                error "Invalid checksum. Got $hash ; expected $CHECKSUM-$arch ($?)" 104
             fi
             echo "File integrity validated"
         }
@@ -102,7 +108,7 @@ runs:
 
             echo "Downloading from: $DOWNLOAD_URL"
             download "$DOWNLOAD_URL" "$TEMP_FILE"
-            check_file "$TEMP_FILE"
+            check_file "$TEMP_FILE" "${OS}-${ARCH}"
 
             # Rename and make executable
             FINAL_FILE="${INSTALL_DIR}/safe-chain"
@@ -127,4 +133,5 @@ runs:
         main "$@"
       env:
         VERSION: ${{ inputs.version }}
-        CHECKSUM: ${{ inputs.checksum }}
+        CHECKSUM-linux-x64: ${{ inputs.checksum-linux-x64 }}
+        CHECKSUM-macos-arm64: ${{ inputs.checksum-macos-arm64 }}
